name: beaver_learning
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  webview_flutter: ^4.4.4
  font_awesome_flutter: ^10.6.0
  dio: ^5.4.1
  shelf_static: ^1.1.2
  transparent_image: ^2.0.1

  flutter_quill: ^9.2.3
  #dart_quill_delta: ^9.3.1
  quill_html_converter: ^9.2.3
  flutter_quill_extensions: ^9.2.3

  image_cropper: ^5.0.1
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.4
  hydrated_bloc: ^9.1.4
  freezed_annotation: ^2.4.1
  cached_network_image: ^3.3.1

  #drag and drop feature
  #desktop_drop: ^0.4.4

dev_dependencies:
  drift_dev: ^2.14.0
  build_runner: ^2.4.7
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/flashmemorizepro.png"
  ios:
    generate: true
    icon_size: 256
    background_color: "#09EFC1"
    theme_color: "#09EFC1"
  android:
    generate: true
    icon_size: 256
    background_color: "#09EFC1"
    theme_color: "#09EFC1"